package by.tc.web.controller;

public enum  CommandName {
    AUTHENTICATION,
    REGISTRATION,
    LOCALIZATION,
    LOGOUT,
    EDIT_ACCOUNT,
    DELETE_ACCOUNT,
    SHOW_ALL_USERS,
    SHOW_ALL_DRIVERS,
    SHOW_ALL_ORDERS,
    SHOW_ALL_ADMINS,
    DRIVER_REGISTRATION,
    ADMIN_REGISTRATION,
    BLOCK_USER,
    UNBLOCK_USER,
    CONFIRM_DRIVER,
    BLOCK_DRIVER,
    UNBLOCK_DRIVER,
    CREATE_ORDER,
    FIND_DRIVER,
    CHOOSE_ORDER,
    ACCEPT_ORDER,
    DECLINE_ORDER,
    FINISH_ORDER,
    ON_ROUTE_ORDER,
    CHECK_STATUS,
    DELETE_ADMIN,
    CHECK_ACTIVER_CUSTOMER_ORDER


}
